import {
  AppWindow,
  BadgeDollarSign,
  BarChart3,
  Blocks,
  BookOpenText,
  Bot,
  Boxes,
  BrainCircuit,
  Braces,
  BriefcaseBusiness,
  Building,
  Building2,
  CalendarRange,
  ChartNoAxesCombined,
  CircuitBoard,
  ClipboardCheck,
  CodeXml,
  Component,
  ContactRound,
  Code2,
  Compass,
  Crosshair,
  Database,
  ExternalLink,
  FileCog,
  FilePenLine,
  FileSearch,
  Files,
  FileText,
  Fingerprint,
  GalleryVerticalEnd,
  Gauge,
  GitFork,
  GitPullRequest,
  Globe,
  Globe2,
  Handshake,
  Headphones,
  Image,
  Languages,
  Layers3,
  LayoutTemplate,
  LayoutPanelTop,
  LibraryBig,
  LifeBuoy,
  Lightbulb,
  ListChecks,
  ListFilterPlus,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircleQuestion,
  MessagesSquare,
  MonitorPlay,
  MousePointer2,
  Network,
  Newspaper,
  NotebookTabs,
  Palette,
  PanelTop,
  PanelsTopLeft,
  PlugZap,
  RefreshCw,
  Route,
  Rss,
  ScanSearch,
  ScanText,
  Search,
  SearchCheck,
  Send,
  Settings,
  Settings2,
  Shapes,
  Share2,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquareTerminal,
  Tags,
  TextCursorInput,
  TrendingUp,
  UserRoundCheck,
  Workflow,
  Wrench,
} from "lucide-react";

const CATEGORY_ICONS = {
  "web-development": Code2,
  "mobile-app-development": Smartphone,
  "ui-ux-design": Palette,
  "search-optimization": Search,
  "ai-automation": Bot,
  "branding-marketing-selling": Megaphone,
  "content-creative": FileText,
  "e-commerce-solutions": ShoppingCart,
  "analytics-data-intelligence": BarChart3,
  "digital-systems": Settings,
  "strategy-digital-transformation": Compass,
  "support-growth": Wrench,
};

const CATEGORY_ORDER = Object.keys(CATEGORY_ICONS);

const CHILD_ICONS = [
  PanelsTopLeft,
  Building2,
  Braces,
  LayoutTemplate,
  GalleryVerticalEnd,
  BriefcaseBusiness,
  AppWindow,
  Database,
  Blocks,
  FileCog,
  RefreshCw,
  Gauge,
  ShieldCheck,
  Workflow,
  ChartNoAxesCombined,
];

// Each service in the six-folder homepage catalog has one deliberately chosen,
// non-repeating icon. Keeping this keyed by slug makes the visual meaning stable
// when services are reordered or localized.
const SERVICE_ICONS = {
  "web-development-corporate-website-development": Building2,
  "web-development-company-profile-website": ContactRound,
  "web-development-custom-website-development": CodeXml,
  "web-development-landing-page-development": PanelsTopLeft,
  "web-development-portfolio-website-development": GalleryVerticalEnd,
  "web-development-business-website-development": BriefcaseBusiness,
  "web-development-web-application-development": AppWindow,
  "web-development-cms-development": Database,
  "web-development-headless-cms-development": Boxes,
  "web-development-wordpress-development": Layers3,
  "web-development-website-migration-and-modernization": RefreshCw,
  "web-development-website-maintenance": Wrench,

  "ui-ux-design-ui-design": Palette,
  "ui-ux-design-ux-design": MousePointer2,
  "ui-ux-design-ux-audit": ScanSearch,
  "ui-ux-design-ui-audit": ListChecks,
  "ui-ux-design-product-design": Shapes,
  "ui-ux-design-design-system-development": Component,
  "ui-ux-design-wireframing": LayoutPanelTop,
  "ui-ux-design-interactive-prototype": MonitorPlay,
  "ui-ux-design-user-flow-design": Workflow,
  "ui-ux-design-information-architecture": Network,

  "search-optimization-seo-audit": SearchCheck,
  "search-optimization-technical-seo": FileCog,
  "search-optimization-on-page-seo": FileSearch,
  "search-optimization-off-page-seo": ExternalLink,
  "search-optimization-local-seo": MapPin,
  "search-optimization-international-seo": Globe,
  "search-optimization-enterprise-seo": Building,
  "search-optimization-e-commerce-seo": ShoppingCart,
  "search-optimization-seo-content-strategy": BookOpenText,
  "search-optimization-answer-engine-optimization-aeo": MessageCircleQuestion,
  "search-optimization-generative-engine-optimization-geo": Sparkles,
  "search-optimization-knowledge-graph-optimization": GitFork,
  "search-optimization-entity-seo": Tags,
  "search-optimization-seo-recovery": LifeBuoy,
  "search-optimization-seo-monitoring-and-reporting": ChartNoAxesCombined,

  "ai-automation-ai-strategy-consulting": BrainCircuit,
  "ai-automation-ai-workflow-automation": GitPullRequest,
  "ai-automation-ai-agent-development": Bot,
  "ai-automation-ai-chatbot-development": MessagesSquare,
  "ai-automation-prompt-engineering": SquareTerminal,
  "ai-automation-business-process-automation": Settings2,
  "ai-automation-workflow-integration": PlugZap,
  "ai-automation-knowledge-base-development": LibraryBig,
  "ai-automation-ai-document-processing": ScanText,
  "ai-automation-ai-customer-support": Headphones,
  "ai-automation-ai-content-workflow": Files,
  "ai-automation-custom-ai-solution-development": CircuitBoard,

  "branding-marketing-selling-brand-strategy": Compass,
  "branding-marketing-selling-brand-identity": Fingerprint,
  "branding-marketing-selling-brand-positioning": Crosshair,
  "branding-marketing-selling-marketing-strategy": Map,
  "branding-marketing-selling-digital-marketing-strategy": Megaphone,
  "branding-marketing-selling-search-engine-marketing-sem": BadgeDollarSign,
  "branding-marketing-selling-performance-marketing": Gauge,
  "branding-marketing-selling-social-media-marketing": Share2,
  "branding-marketing-selling-content-marketing": Newspaper,
  "branding-marketing-selling-email-marketing": Mail,
  "branding-marketing-selling-sales-funnel-development": ListFilterPlus,
  "branding-marketing-selling-conversion-rate-optimization-cro": TrendingUp,
  "branding-marketing-selling-personal-branding": UserRoundCheck,
  "branding-marketing-selling-customer-journey-optimization": Route,
  "branding-marketing-selling-sales-strategy-development": Handshake,

  "content-creative-seo-content-writing": FilePenLine,
  "content-creative-website-copywriting": TextCursorInput,
  "content-creative-content-strategy": NotebookTabs,
  "content-creative-editorial-planning": CalendarRange,
  "content-creative-blog-management": Rss,
  "content-creative-content-localization": Languages,
  "content-creative-creative-campaign-planning": Lightbulb,
  "content-creative-visual-content-design": Image,
  "content-creative-landing-page-copywriting": PanelTop,
  "content-creative-email-copywriting": Send,
  "content-creative-content-audit": ClipboardCheck,
  "content-creative-content-optimization": SlidersHorizontal,
};

export function getServiceCategoryIcon(slug) {
  return CATEGORY_ICONS[slug] || Globe2;
}

export function getServiceChildIcon(index, parentSlug, serviceSlug) {
  if (serviceSlug && SERVICE_ICONS[serviceSlug]) return SERVICE_ICONS[serviceSlug];
  const categoryOffset = Math.max(0, CATEGORY_ORDER.indexOf(parentSlug));
  return CHILD_ICONS[(index + categoryOffset) % CHILD_ICONS.length];
}
